name: Latest blog post workflow
on:
    push:
         branches: master 
    schedule: # Run workflow automatically
        - cron: '0 0 * * 1' # Runs every monday, on 00:00
    workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                max_post_count: "5" 
                feed_list: "https://www.gsavitha.in/posts/index.xml"

